### ISSUE TITLE
Better graphics

### ISSUE THREAD

**Issue by raae** [lillylabs/profile-pic-overlay#25]
I have used the exported files I found in the shared folder, but they are not all of great quality. I am not that familiar with sketch so have not tried to export myself.

- Need the filters in high resolution 1600x1600 pixels. Also the "norwegian women"'s filer is a little rotated, there is a glitch in bottom left corner.
- The logos need to be exported in same color quality.

**Comment by isabelleringnes** [comment]
Do you mean the filters or images? I have uploaded the filters in EPS format in a folder in the drive called Filters High Res together with the two logos in High res.

**Comment by raae** [comment]
I do not know what is happening, but the esp I am getting are not good. Send over you sketch master file again and I will figure it out.
