### ISSUE TITLE
Facebook Business

### ISSUE THREAD

**Issue by raae** [lillylabs/profile-pic-overlay#40]
Move the apps into the business account. You should be allowed now that you are an admin of the apps. When this is done the "business account" becomes the owner and not any of us personally.

You can also do this with pages you create for the campaign.

Also invite me (benedicte@lillylabs.no) as an employee under people.

**Comment by isabelleringnes** [comment]
I have added both pages to the business manager and added you as an employee. Let me know if you need more access. Do I add the apps as seperate apps with the url you sent me? Might need some explanation here.

**Comment by raae** [comment]
You add the apps the same way you added the pages, I think. Or you give me admin access and I do it. You can downgrade med to employee later again.

<img width="603" alt="business_manager" src="https://user-images.githubusercontent.com/478531/28712965-7b291b92-738d-11e7-9f8a-56ce5cfd8315.png">

**Comment by isabelleringnes** [comment]
I was able to add itshertreatfilter, but not the hunspandererfilter, because I dont have the app id from netlify. Could you send it to me? I am back in Oslo the 3rd, big flight confusion.
