### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by perrygovier** [lillylabs/profile-pic-overlay#61]
Hello!

I am volunteering with the Democratic Party of Wisconsin in the USA, and I'd like to use this as a starting point to build a profile pic overlay generator for the Joe Biden campaign here in Wisconsin, as well as for some local Democratic Party candidates. I would like to ask since your repo does not have a license file, would it be ok if I use this code? 

Regards, 

Perry Govier
@perrygovier

**Comment by raae** [comment]
I had almost forgotten about this repo, I will check with my original client on  this and get back to you.

**Comment by olavea** [comment]
Hi @perrygovier 😸 

Benedicte @raae asked me to contact our client and I just sent her and SMS. 

When she answers "yes", why don't you just 
make a pull request with an appropriate license?

So how much of a hurry are you in? 
Seems to me the election is right around the corner, no?

**Comment by olavea** [comment]
Hi @perrygovier 

Yeah the client said yes. 😸 👍 

So why don't you just 
make a pull request with an MIT license?

How does that sound for you?

**Comment by perrygovier** [comment]
Thank you very much. I wanted to let you know the website is live. Thank you so much for letting me use this as a starting place. You can see it at: https://wisde.ms
